### ISSUE TITLE
[Bug] Resource Import Texture Missing

### ISSUE THREAD

**Issue by oeccsy** [Fouractal/Fermi-paradox#9]
### 재현 환경
- Unity Editor 2021.3.40f1

### 재현 과정
- 전달 받은 fbx 파일 import
- import 한 파일을 scene에 배치

### 오류 내용
- scene에 배치한 오브젝트에 `texture`가 입혀져 있지 않음
![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/98cd8624-7e0a-4a81-a601-1d18c0297092)

- `texture`를 적용하기 위해 `Extract Textures` 를 진행하려 했으나 불가능
![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/d8d6f923-1a12-4a85-9db3-2360117c5bfb)

### 기대 결과
- `texture` 적용되어 회의에서 전달 받은 결과물의 모습으로 렌더링

### 기타 자료
- `blender`에서 export 하는 과정에서 path mode -> `Copy` , `embed textures` 옵션 포함 하는 경우 해결할 수 있을 것으로 예상함

![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/89c1306a-b8cc-49d3-9064-1355307a9d61)

- 참고 레퍼런스 링크 :  https://www.youtube.com/watch?v=BYf4QnzXynQ&t=59s

**Comment by kkkkiiiiii** [comment]
- 전달 받은 material에는 color, uv mapping 가 적용된 상태
    - 기존의 ClipFromCharacter Shader의 기능을 사용하면서 import 한 material의 color, uv mapping까지 이뤄져야 함
    -  기존의 ClipFromCharacter Shader 에 Texture만 추가하여 사용하는 경우 import 한 Asset을 Scene에 배치하여 확인했을 때와 다름.
    - `UV mapping`, `color` 적용 부분 수정 필요
    - 사용하는 모든 material에 대하여 대응

### import한 초기 상태
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/f0a8b36e-d1f1-44a7-bb15-ff08d7b8c644)

### material에 ClipFromCharacter Shader 적용한 상태
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/5718cd45-a6d6-4f49-8112-00b47248d410)

### Standar vs ClipFromCharacter
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/a31310d2-a521-48ac-9805-c6b1762f13ec)

### 반투명 
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/9f14cd3b-1a77-4c01-8cb1-00daec0122f5)

**Comment by kkkkiiiiii** [comment]
# ClipFromCharacter Shader 수정 요망
- light 반영되도록 수정 필요

## ClipFromCharacter Shader 적용된 상태
- 씬 내 light가 반영 안 됨.
    - Unlit Shader 기반으로 만든 것이 원인인 걸로 추정
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/00d0e1a5-29c2-403e-ac73-c1d5ae094df6)


### ClipFromCharacter Shader에 Color, Intensity추가
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/2040c0f9-8ef9-45ae-88b3-7c80a956e50b)

**Comment by kkkkiiiiii** [comment]
### ClipFromCharacter Shader 적용된 오브젝트 light의 반대편에 이렇게 그림자가 생김

![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/e4bef678-1497-42db-b9cf-d923e5c0372d)
![image](https://github.com/Fouractal/Fermi-paradox/assets/98201682/4050fdd6-2cc0-4836-9df1-45ea16440dc3)

**Comment by oeccsy** [comment]
![image](https://github.com/Fouractal/Fermi-paradox/assets/77562357/19a2ea45-681a-4fa0-a84d-c5d3d1f2d17d)

cast shadows

**Comment by oeccsy** [comment]
`Extract Texture`, `Extract Material` 순서로 진행하면, Material에 필요한 Texture가 입혀진 상태로 생성됨

**Comment by oeccsy** [comment]
Texture 이슈가 해결되어 Close
